name: Deploy terraform infrastructure

on:
    workflow_dispatch:
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
        TF_VAR_organization_id: ${{ secrets.ORGANIZATION_ID }}
        TF_VAR_public_key: ${{ secrets.PUBLIC_KEY }}
        TF_VAR_private_key: ${{ secrets.PRIVATE_KEY }}
        TF_VAR_payment_db_username: ${{ secrets.PAYMENT_DB_USERNAME }}
        TF_VAR_payment_db_password: ${{ secrets.PAYMENT_DB_PASSWORD }}
        TF_VAR_kitchen_db_username: ${{ secrets.KITCHEN_DB_USERNAME }}
        TF_VAR_kitchen_db_password: ${{ secrets.KITCHEN_DB_PASSWORD }}
        TF_VAR_customer_db_username: ${{ secrets.CUSTOMER_DB_USERNAME }}
        TF_VAR_customer_db_password: ${{ secrets.CUSTOMER_DB_PASSWORD }}
    defaults:
      run:
        working-directory: ./infra 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.SESSION_TOKEN }} 

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3

      - name: Load providers and modules
        run: terraform init

      - name: Apply changes on the providers
        run: terraform apply --auto-approve 